package com.smiley.gita.notocoloremojies.emojies

import com.smiley.gita.notocoloremojies.Utils

class AnimalNature {

    companion object {

        fun getNatureSmiley(): ArrayList<String>? {

            val emojis : ArrayList<String>? = ArrayList()

            emojis?.add(Utils.getString(0x1F435))
            emojis?.add(Utils.getString(0x1F412))
            emojis?.add(Utils.getString(0x1F98D))
            emojis?.add(Utils.getString(0x1F436))
            emojis?.add(Utils.getString(0x1F415))
            emojis?.add(Utils.getString(0x1F429))
            emojis?.add(Utils.getString(0x1F43A))
            emojis?.add(Utils.getString(0x1F98A))
            emojis?.add(Utils.getString(0x1F431))
            emojis?.add(Utils.getString(0x1F408))
            emojis?.add(Utils.getString(0x1F981))
            emojis?.add(Utils.getString(0x1F42F))
            emojis?.add(Utils.getString(0x1F405))
            emojis?.add(Utils.getString(0x1F406))
            emojis?.add(Utils.getString(0x1F434))
            emojis?.add(Utils.getString(0x1F40E))
            emojis?.add(Utils.getString(0x1F984))
            emojis?.add(Utils.getString(0x1F993))
            emojis?.add(Utils.getString(0x1F98C))
            emojis?.add(Utils.getString(0x1F42E))
            emojis?.add(Utils.getString(0x1F402))
            emojis?.add(Utils.getString(0x1F403))
            emojis?.add(Utils.getString(0x1F404))
            emojis?.add(Utils.getString(0x1F437))
            emojis?.add(Utils.getString(0x1F416))
            emojis?.add(Utils.getString(0x1F417))
            emojis?.add(Utils.getString(0x1F43D))
            emojis?.add(Utils.getString(0x1F40F))
            emojis?.add(Utils.getString(0x1F411))
            emojis?.add(Utils.getString(0x1F410))
            emojis?.add(Utils.getString(0x1F42A))
            emojis?.add(Utils.getString(0x1F42B))
            emojis?.add(Utils.getString(0x1F992))
            emojis?.add(Utils.getString(0x1F418))
            emojis?.add(Utils.getString(0x1F98F))
            emojis?.add(Utils.getString(0x1F42D))
            emojis?.add(Utils.getString(0x1F401))
            emojis?.add(Utils.getString(0x1F400))
            emojis?.add(Utils.getString(0x1F439))
            emojis?.add(Utils.getString(0x1F430))
            emojis?.add(Utils.getString(0x1F407))
            emojis?.add(Utils.getString(0x1F43F))
            emojis?.add(Utils.getString(0x1F994))
            emojis?.add(Utils.getString(0x1F987))
            emojis?.add(Utils.getString(0x1F43B))
            emojis?.add(Utils.getString(0x1F428))
            emojis?.add(Utils.getString(0x1F43C))
            emojis?.add(Utils.getString(0x1F43E))
            emojis?.add(Utils.getString(0x1F983))
            emojis?.add(Utils.getString(0x1F414))
            emojis?.add(Utils.getString(0x1F413))
            emojis?.add(Utils.getString(0x1F423))
            emojis?.add(Utils.getString(0x1F424))
            emojis?.add(Utils.getString(0x1F425))
            emojis?.add(Utils.getString(0x1F426))
            emojis?.add(Utils.getString(0x1F427))
            emojis?.add(Utils.getString(0x1F54A))
            emojis?.add(Utils.getString(0x1F985))
            emojis?.add(Utils.getString(0x1F986))
            emojis?.add(Utils.getString(0x1F989))
            emojis?.add(Utils.getString(0x1F438))
            emojis?.add(Utils.getString(0x1F40A))
            emojis?.add(Utils.getString(0x1F422))
            emojis?.add(Utils.getString(0x1F98E))
            emojis?.add(Utils.getString(0x1F40D))
            emojis?.add(Utils.getString(0x1F432))
            emojis?.add(Utils.getString(0x1F409))
            emojis?.add(Utils.getString(0x1F995))
            emojis?.add(Utils.getString(0x1F996))
            emojis?.add(Utils.getString(0x1F433))
            emojis?.add(Utils.getString(0x1F40B))
            emojis?.add(Utils.getString(0x1F42C))
            emojis?.add(Utils.getString(0x1F41F))
            emojis?.add(Utils.getString(0x1F420))
            emojis?.add(Utils.getString(0x1F421))
            emojis?.add(Utils.getString(0x1F988))
            emojis?.add(Utils.getString(0x1F419))
            emojis?.add(Utils.getString(0x1F41A))
            emojis?.add(Utils.getString(0x1F980))
            emojis?.add(Utils.getString(0x1F990))
            emojis?.add(Utils.getString(0x1F991))
            emojis?.add(Utils.getString(0x1F40C))
            emojis?.add(Utils.getString(0x1F98B))
            emojis?.add(Utils.getString(0x1F41B))
            emojis?.add(Utils.getString(0x1F41C))
            emojis?.add(Utils.getString(0x1F41D))
            emojis?.add(Utils.getString(0x1F41E))
            emojis?.add(Utils.getString(0x1F997))
            emojis?.add(Utils.getString(0x1F577))
            emojis?.add(Utils.getString(0x1F578))
            emojis?.add(Utils.getString(0x1F982))
            emojis?.add(Utils.getString(0x1F490))
            emojis?.add(Utils.getString(0x1F338))
            emojis?.add(Utils.getString(0x1F4AE))
            emojis?.add(Utils.getString(0x1F3F5))
            emojis?.add(Utils.getString(0x1F339))
            emojis?.add(Utils.getString(0x1F940))
            emojis?.add(Utils.getString(0x1F33A))
            emojis?.add(Utils.getString(0x1F33B))
            emojis?.add(Utils.getString(0x1F33C))
            emojis?.add(Utils.getString(0x1F337))
            emojis?.add(Utils.getString(0x1F331))
            emojis?.add(Utils.getString(0x1F332))
            emojis?.add(Utils.getString(0x1F333))
            emojis?.add(Utils.getString(0x1F334))
            emojis?.add(Utils.getString(0x1F335))
            emojis?.add(Utils.getString(0x1F33E))
            emojis?.add(Utils.getString(0x1F33F))
            emojis?.add(Utils.getString(0x2618))
            emojis?.add(Utils.getString(0x1F340))
            emojis?.add(Utils.getString(0x1F341))
            emojis?.add(Utils.getString(0x1F342))
            emojis?.add(Utils.getString(0x1F343))

            return emojis

        }

    }

}