package com.smiley.gita.notocoloremojies.emojies

import com.smiley.gita.notocoloremojies.Utils

class FoodDrink {

    companion object {

        fun getFoodDrinkSmiley(): ArrayList<String>? {

            val emojis : ArrayList<String>? = ArrayList()
            emojis?.add(Utils.getString(0x1F347))
            emojis?.add(Utils.getString(0x1F348))
            emojis?.add(Utils.getString(0x1F349))
            emojis?.add(Utils.getString(0x1F34A))
            emojis?.add(Utils.getString(0x1F34B))
            emojis?.add(Utils.getString(0x1F34C))
            emojis?.add(Utils.getString(0x1F34D))
            emojis?.add(Utils.getString(0x1F34E))
            emojis?.add(Utils.getString(0x1F34F))
            emojis?.add(Utils.getString(0x1F350))
            emojis?.add(Utils.getString(0x1F351))
            emojis?.add(Utils.getString(0x1F352))
            emojis?.add(Utils.getString(0x1F353))
            emojis?.add(Utils.getString(0x1F95D))
            emojis?.add(Utils.getString(0x1F345))
            emojis?.add(Utils.getString(0x1F965))
            emojis?.add(Utils.getString(0x1F951))
            emojis?.add(Utils.getString(0x1F346))
            emojis?.add(Utils.getString(0x1F954))
            emojis?.add(Utils.getString(0x1F955))
            emojis?.add(Utils.getString(0x1F33D))
            emojis?.add(Utils.getString(0x1F336))
            emojis?.add(Utils.getString(0x1F952))
            emojis?.add(Utils.getString(0x1F966))
            emojis?.add(Utils.getString(0x1F344))
            emojis?.add(Utils.getString(0x1F95C))
            emojis?.add(Utils.getString(0x1F330))
            emojis?.add(Utils.getString(0x1F35E))
            emojis?.add(Utils.getString(0x1F950))
            emojis?.add(Utils.getString(0x1F956))
            emojis?.add(Utils.getString(0x1F968))
            emojis?.add(Utils.getString(0x1F95E))
            emojis?.add(Utils.getString(0x1F9C0))
            emojis?.add(Utils.getString(0x1F356))
            emojis?.add(Utils.getString(0x1F357))
            emojis?.add(Utils.getString(0x1F969))
            emojis?.add(Utils.getString(0x1F953))
            emojis?.add(Utils.getString(0x1F354))
            emojis?.add(Utils.getString(0x1F35F))
            emojis?.add(Utils.getString(0x1F355))
            emojis?.add(Utils.getString(0x1F32D))
            emojis?.add(Utils.getString(0x1F96A))
            emojis?.add(Utils.getString(0x1F32E))
            emojis?.add(Utils.getString(0x1F32F))
            emojis?.add(Utils.getString(0x1F959))
            emojis?.add(Utils.getString(0x1F95A))
            emojis?.add(Utils.getString(0x1F373))
            emojis?.add(Utils.getString(0x1F958))
            emojis?.add(Utils.getString(0x1F372))
            emojis?.add(Utils.getString(0x1F963))
            emojis?.add(Utils.getString(0x1F957))
            emojis?.add(Utils.getString(0x1F37F))
            emojis?.add(Utils.getString(0x1F96B))
            emojis?.add(Utils.getString(0x1F371))
            emojis?.add(Utils.getString(0x1F358))
            emojis?.add(Utils.getString(0x1F359))
            emojis?.add(Utils.getString(0x1F35A))
            emojis?.add(Utils.getString(0x1F35B))
            emojis?.add(Utils.getString(0x1F35C))
            emojis?.add(Utils.getString(0x1F35D))
            emojis?.add(Utils.getString(0x1F360))
            emojis?.add(Utils.getString(0x1F362))
            emojis?.add(Utils.getString(0x1F363))
            emojis?.add(Utils.getString(0x1F364))
            emojis?.add(Utils.getString(0x1F365))
            emojis?.add(Utils.getString(0x1F361))
            emojis?.add(Utils.getString(0x1F95F))
            emojis?.add(Utils.getString(0x1F960))
            emojis?.add(Utils.getString(0x1F961))
            emojis?.add(Utils.getString(0x1F366))
            emojis?.add(Utils.getString(0x1F367))
            emojis?.add(Utils.getString(0x1F368))
            emojis?.add(Utils.getString(0x1F369))
            emojis?.add(Utils.getString(0x1F36A))
            emojis?.add(Utils.getString(0x1F382))
            emojis?.add(Utils.getString(0x1F370))
            emojis?.add(Utils.getString(0x1F967))
            emojis?.add(Utils.getString(0x1F36B))
            emojis?.add(Utils.getString(0x1F36C))
            emojis?.add(Utils.getString(0x1F36D))
            emojis?.add(Utils.getString(0x1F36E))
            emojis?.add(Utils.getString(0x1F36F))
            emojis?.add(Utils.getString(0x1F37C))
            emojis?.add(Utils.getString(0x1F95B))
            emojis?.add(Utils.getString(0x2615))
            emojis?.add(Utils.getString(0x1F375))
            emojis?.add(Utils.getString(0x1F376))
            emojis?.add(Utils.getString(0x1F37E))
            emojis?.add(Utils.getString(0x1F377))
            emojis?.add(Utils.getString(0x1F378))
            emojis?.add(Utils.getString(0x1F379))
            emojis?.add(Utils.getString(0x1F37A))
            emojis?.add(Utils.getString(0x1F37B))
            emojis?.add(Utils.getString(0x1F942))
            emojis?.add(Utils.getString(0x1F943))
            emojis?.add(Utils.getString(0x1F964))
            emojis?.add(Utils.getString(0x1F962))
            emojis?.add(Utils.getString(0x1F37D))
            emojis?.add(Utils.getString(0x1F374))
            emojis?.add(Utils.getString(0x1F944))
            emojis?.add(Utils.getString(0x1F52A))
            emojis?.add(Utils.getString(0x1F3FA))

            return emojis

        }

    }

}