package com.smiley.gita.notocoloremojies.emojies

import com.smiley.gita.notocoloremojies.Utils

class Object {

    companion object {

        fun getObjectsSmiley(): ArrayList<String>? {

            val emojis : ArrayList<String>? = ArrayList()

            emojis?.add(Utils.getString(0x1F507))
            emojis?.add(Utils.getString(0x1F508))
            emojis?.add(Utils.getString(0x1F509))
            emojis?.add(Utils.getString(0x1F50A))
            emojis?.add(Utils.getString(0x1F4E2))
            emojis?.add(Utils.getString(0x1F4E3))
            emojis?.add(Utils.getString(0x1F4EF))
            emojis?.add(Utils.getString(0x1F514))
            emojis?.add(Utils.getString(0x1F515))
            emojis?.add(Utils.getString(0x1F3BC))
            emojis?.add(Utils.getString(0x1F3B5))
            emojis?.add(Utils.getString(0x1F3B6))
            emojis?.add(Utils.getString(0x1F399))
            emojis?.add(Utils.getString(0x1F39A))
            emojis?.add(Utils.getString(0x1F39B))
            emojis?.add(Utils.getString(0x1F3A4))
            emojis?.add(Utils.getString(0x1F3A7))
            emojis?.add(Utils.getString(0x1F4FB))
            emojis?.add(Utils.getString(0x1F3B7))
            emojis?.add(Utils.getString(0x1F3B8))
            emojis?.add(Utils.getString(0x1F3B9))
            emojis?.add(Utils.getString(0x1F3BA))
            emojis?.add(Utils.getString(0x1F3BB))
            emojis?.add(Utils.getString(0x1F941))
            emojis?.add(Utils.getString(0x1F4F1))
            emojis?.add(Utils.getString(0x1F4F2))
            emojis?.add(Utils.getString(0x260E))
            emojis?.add(Utils.getString(0x1F4DE))
            emojis?.add(Utils.getString(0x1F4DF))
            emojis?.add(Utils.getString(0x1F4E0))
            emojis?.add(Utils.getString(0x1F50B))
            emojis?.add(Utils.getString(0x1F50C))
            emojis?.add(Utils.getString(0x1F4BB))
            emojis?.add(Utils.getString(0x1F5A5))
            emojis?.add(Utils.getString(0x1F5A8))
            emojis?.add(Utils.getString(0x2328))
            emojis?.add(Utils.getString(0x1F5B1))
            emojis?.add(Utils.getString(0x1F5B2))
            emojis?.add(Utils.getString(0x1F4BD))
            emojis?.add(Utils.getString(0x1F4BE))
            emojis?.add(Utils.getString(0x1F4BF))
            emojis?.add(Utils.getString(0x1F4C0))
            emojis?.add(Utils.getString(0x1F3A5))
            emojis?.add(Utils.getString(0x1F39E))
            emojis?.add(Utils.getString(0x1F4FD))
            emojis?.add(Utils.getString(0x1F3AC))
            emojis?.add(Utils.getString(0x1F4FA))
            emojis?.add(Utils.getString(0x1F4F7))
            emojis?.add(Utils.getString(0x1F4F8))
            emojis?.add(Utils.getString(0x1F4F9))
            emojis?.add(Utils.getString(0x1F4FC))
            emojis?.add(Utils.getString(0x1F50D))
            emojis?.add(Utils.getString(0x1F50E))
            emojis?.add(Utils.getString(0x1F52C))
            emojis?.add(Utils.getString(0x1F52D))
            emojis?.add(Utils.getString(0x1F4E1))
            emojis?.add(Utils.getString(0x1F56F))
            emojis?.add(Utils.getString(0x1F4A1))
            emojis?.add(Utils.getString(0x1F526))
            emojis?.add(Utils.getString(0x1F3EE))
            emojis?.add(Utils.getString(0x1F4D4))
            emojis?.add(Utils.getString(0x1F4D5))
            emojis?.add(Utils.getString(0x1F4D6))
            emojis?.add(Utils.getString(0x1F4D7))
            emojis?.add(Utils.getString(0x1F4D8))
            emojis?.add(Utils.getString(0x1F4D9))
            emojis?.add(Utils.getString(0x1F4DA))
            emojis?.add(Utils.getString(0x1F4D3))
            emojis?.add(Utils.getString(0x1F4D2))
            emojis?.add(Utils.getString(0x1F4C3))
            emojis?.add(Utils.getString(0x1F4DC))
            emojis?.add(Utils.getString(0x1F4C4))
            emojis?.add(Utils.getString(0x1F4F0))
            emojis?.add(Utils.getString(0x1F5DE))
            emojis?.add(Utils.getString(0x1F4D1))
            emojis?.add(Utils.getString(0x1F516))
            emojis?.add(Utils.getString(0x1F3F7))
            emojis?.add(Utils.getString(0x1F4B0))
            emojis?.add(Utils.getString(0x1F4B4))
            emojis?.add(Utils.getString(0x1F4B5))
            emojis?.add(Utils.getString(0x1F4B6))
            emojis?.add(Utils.getString(0x1F4B7))
            emojis?.add(Utils.getString(0x1F4B8))
            emojis?.add(Utils.getString(0x1F4B3))
            emojis?.add(Utils.getString(0x1F4B9))
            emojis?.add(Utils.getString(0x1F4B1))
            emojis?.add(Utils.getString(0x1F4B2))
            emojis?.add(Utils.getString(0x2709))
            emojis?.add(Utils.getString(0x1F4E7))
            emojis?.add(Utils.getString(0x1F4E8))
            emojis?.add(Utils.getString(0x1F4E9))
            emojis?.add(Utils.getString(0x1F4E4))
            emojis?.add(Utils.getString(0x1F4E5))
            emojis?.add(Utils.getString(0x1F4E6))
            emojis?.add(Utils.getString(0x1F4EB))
            emojis?.add(Utils.getString(0x1F4EA))
            emojis?.add(Utils.getString(0x1F4EC))
            emojis?.add(Utils.getString(0x1F4ED))
            emojis?.add(Utils.getString(0x1F4EE))
            emojis?.add(Utils.getString(0x1F5F3))
            emojis?.add(Utils.getString(0x270F))
            emojis?.add(Utils.getString(0x2712))
            emojis?.add(Utils.getString(0x1F58B))
            emojis?.add(Utils.getString(0x1F58A))
            emojis?.add(Utils.getString(0x1F58C))
            emojis?.add(Utils.getString(0x1F58D))
            emojis?.add(Utils.getString(0x1F4DD))
            emojis?.add(Utils.getString(0x1F4BC))
            emojis?.add(Utils.getString(0x1F4C1))
            emojis?.add(Utils.getString(0x1F4C2))
            emojis?.add(Utils.getString(0x1F5C2))
            emojis?.add(Utils.getString(0x1F4C5))
            emojis?.add(Utils.getString(0x1F4C6))
            emojis?.add(Utils.getString(0x1F5D2))
            emojis?.add(Utils.getString(0x1F5D3))
            emojis?.add(Utils.getString(0x1F4C7))
            emojis?.add(Utils.getString(0x1F4C8))
            emojis?.add(Utils.getString(0x1F4C9))
            emojis?.add(Utils.getString(0x1F4CA))
            emojis?.add(Utils.getString(0x1F4CB))
            emojis?.add(Utils.getString(0x1F4CC))
            emojis?.add(Utils.getString(0x1F4CD))
            emojis?.add(Utils.getString(0x1F4CE))
            emojis?.add(Utils.getString(0x1F587))
            emojis?.add(Utils.getString(0x1F4CF))
            emojis?.add(Utils.getString(0x1F4D0))
            emojis?.add(Utils.getString(0x2702))
            emojis?.add(Utils.getString(0x1F5C3))
            emojis?.add(Utils.getString(0x1F5C4))
            emojis?.add(Utils.getString(0x1F5D1))
            emojis?.add(Utils.getString(0x1F512))
            emojis?.add(Utils.getString(0x1F513))
            emojis?.add(Utils.getString(0x1F50F))
            emojis?.add(Utils.getString(0x1F510))
            emojis?.add(Utils.getString(0x1F511))
            emojis?.add(Utils.getString(0x1F5DD))
            emojis?.add(Utils.getString(0x1F528))
            emojis?.add(Utils.getString(0x26CF))
            emojis?.add(Utils.getString(0x2692))
            emojis?.add(Utils.getString(0x1F6E0))
            emojis?.add(Utils.getString(0x1F5E1))
            emojis?.add(Utils.getString(0x2694))
            emojis?.add(Utils.getString(0x1F52B))
            emojis?.add(Utils.getString(0x1F3F9))
            emojis?.add(Utils.getString(0x1F6E1))
            emojis?.add(Utils.getString(0x1F527))
            emojis?.add(Utils.getString(0x1F529))
            emojis?.add(Utils.getString(0x2699))
            emojis?.add(Utils.getString(0x1F5DC))
            emojis?.add(Utils.getString(0x2697))
            emojis?.add(Utils.getString(0x2696))
            emojis?.add(Utils.getString(0x1F517))
            emojis?.add(Utils.getString(0x26D3))
            emojis?.add(Utils.getString(0x1F489))
            emojis?.add(Utils.getString(0x1F48A))
            emojis?.add(Utils.getString(0x1F6AC))
            emojis?.add(Utils.getString(0x26B0))
            emojis?.add(Utils.getString(0x26B1))
            emojis?.add(Utils.getString(0x1F5FF))
            emojis?.add(Utils.getString(0x1F6E2))
            emojis?.add(Utils.getString(0x1F52E))
            emojis?.add(Utils.getString(0x1F6D2))

            return emojis

        }

    }


}