package com.smiley.gita.notocoloremojies.emojies

import com.smiley.gita.notocoloremojies.Utils

class Symbols {

    companion object {

        fun getSymbolsSmiley(): ArrayList<String>? {

            val emojis : ArrayList<String>? = ArrayList()

            emojis?.add(Utils.getString(0x1F3E7))
            emojis?.add(Utils.getString(0x1F6AE))
            emojis?.add(Utils.getString(0x1F6B0))
            emojis?.add(Utils.getString(0x267F))
            emojis?.add(Utils.getString(0x1F6B9))
            emojis?.add(Utils.getString(0x1F6BA))
            emojis?.add(Utils.getString(0x1F6BB))
            emojis?.add(Utils.getString(0x1F6BC))
            emojis?.add(Utils.getString(0x1F6BE))
            emojis?.add(Utils.getString(0x1F6C2))
            emojis?.add(Utils.getString(0x1F6C3))
            emojis?.add(Utils.getString(0x1F6C4))
            emojis?.add(Utils.getString(0x1F6C5))
            emojis?.add(Utils.getString(0x26A0))
            emojis?.add(Utils.getString(0x1F6B8))
            emojis?.add(Utils.getString(0x26D4))
            emojis?.add(Utils.getString(0x1F6AB))
            emojis?.add(Utils.getString(0x1F6B3))
            emojis?.add(Utils.getString(0x1F6AD))
            emojis?.add(Utils.getString(0x1F6AF))
            emojis?.add(Utils.getString(0x1F6B1))
            emojis?.add(Utils.getString(0x1F6B7))
            emojis?.add(Utils.getString(0x1F4F5))
            emojis?.add(Utils.getString(0x1F51E))
            emojis?.add(Utils.getString(0x2622))
            emojis?.add(Utils.getString(0x2623))
            emojis?.add(Utils.getString(0x2B06))
            emojis?.add(Utils.getString(0x2197))
            emojis?.add(Utils.getString(0x27A1))
            emojis?.add(Utils.getString(0x2198))
            emojis?.add(Utils.getString(0x2B07))
            emojis?.add(Utils.getString(0x2199))
            emojis?.add(Utils.getString(0x2B05))
            emojis?.add(Utils.getString(0x2196))
            emojis?.add(Utils.getString(0x2195))
            emojis?.add(Utils.getString(0x2194))
            emojis?.add(Utils.getString(0x21A9))
            emojis?.add(Utils.getString(0x21AA))
            emojis?.add(Utils.getString(0x2934))
            emojis?.add(Utils.getString(0x2935))
            emojis?.add(Utils.getString(0x1F503))
            emojis?.add(Utils.getString(0x1F504))
            emojis?.add(Utils.getString(0x1F519))
            emojis?.add(Utils.getString(0x1F51A))
            emojis?.add(Utils.getString(0x1F51B))
            emojis?.add(Utils.getString(0x1F51C))
            emojis?.add(Utils.getString(0x1F51D))
            emojis?.add(Utils.getString(0x1F6D0))
            emojis?.add(Utils.getString(0x269B))
            emojis?.add(Utils.getString(0x1F549))
            emojis?.add(Utils.getString(0x2721))
            emojis?.add(Utils.getString(0x2638))
            emojis?.add(Utils.getString(0x262F))
            emojis?.add(Utils.getString(0x271D))
            emojis?.add(Utils.getString(0x2626))
            emojis?.add(Utils.getString(0x262A))
            emojis?.add(Utils.getString(0x262E))
            emojis?.add(Utils.getString(0x1F54E))
            emojis?.add(Utils.getString(0x1F52F))
            emojis?.add(Utils.getString(0x2648))
            emojis?.add(Utils.getString(0x2649))
            emojis?.add(Utils.getString(0x264A))
            emojis?.add(Utils.getString(0x264B))
            emojis?.add(Utils.getString(0x264C))
            emojis?.add(Utils.getString(0x264D))
            emojis?.add(Utils.getString(0x264E))
            emojis?.add(Utils.getString(0x264F))
            emojis?.add(Utils.getString(0x2650))
            emojis?.add(Utils.getString(0x2651))
            emojis?.add(Utils.getString(0x2652))
            emojis?.add(Utils.getString(0x2653))
            emojis?.add(Utils.getString(0x26CE))
            emojis?.add(Utils.getString(0x1F500))
            emojis?.add(Utils.getString(0x1F501))
            emojis?.add(Utils.getString(0x1F502))
            emojis?.add(Utils.getString(0x25B6))
            emojis?.add(Utils.getString(0x23E9))
            emojis?.add(Utils.getString(0x23ED))
            emojis?.add(Utils.getString(0x23EF))
            emojis?.add(Utils.getString(0x25C0))
            emojis?.add(Utils.getString(0x23EA))
            emojis?.add(Utils.getString(0x23EE))
            emojis?.add(Utils.getString(0x1F53C))
            emojis?.add(Utils.getString(0x23EB))
            emojis?.add(Utils.getString(0x1F53D))
            emojis?.add(Utils.getString(0x23EC))
            emojis?.add(Utils.getString(0x23F8))
            emojis?.add(Utils.getString(0x23F9))
            emojis?.add(Utils.getString(0x23FA))
            emojis?.add(Utils.getString(0x23CF))
            emojis?.add(Utils.getString(0x1F3A6))
            emojis?.add(Utils.getString(0x1F505))
            emojis?.add(Utils.getString(0x1F506))
            emojis?.add(Utils.getString(0x1F4F6))
            emojis?.add(Utils.getString(0x1F4F3))
            emojis?.add(Utils.getString(0x1F4F4))
            emojis?.add(Utils.getString(0x2640))
            emojis?.add(Utils.getString(0x2642))
            emojis?.add(Utils.getString(0x2695))
            emojis?.add(Utils.getString(0x267B))
            emojis?.add(Utils.getString(0x269C))
            emojis?.add(Utils.getString(0x1F531))
            emojis?.add(Utils.getString(0x1F4DB))
            emojis?.add(Utils.getString(0x1F530))
            emojis?.add(Utils.getString(0x2B55))
            emojis?.add(Utils.getString(0x2705))
            emojis?.add(Utils.getString(0x2611))
            emojis?.add(Utils.getString(0x2714))
            emojis?.add(Utils.getString(0x2716))
            emojis?.add(Utils.getString(0x274C))
            emojis?.add(Utils.getString(0x274E))
            emojis?.add(Utils.getString(0x2795))
            emojis?.add(Utils.getString(0x2796))
            emojis?.add(Utils.getString(0x2797))
            emojis?.add(Utils.getString(0x27B0))
            emojis?.add(Utils.getString(0x27BF))
            emojis?.add(Utils.getString(0x303D))
            emojis?.add(Utils.getString(0x2733))
            emojis?.add(Utils.getString(0x2734))
            emojis?.add(Utils.getString(0x2747))
            emojis?.add(Utils.getString(0x203C))
            emojis?.add(Utils.getString(0x2049))
            emojis?.add(Utils.getString(0x2753))
            emojis?.add(Utils.getString(0x2754))
            emojis?.add(Utils.getString(0x2755))
            emojis?.add(Utils.getString(0x2757))
            emojis?.add(Utils.getString(0x3030))
            emojis?.add(Utils.getString(0xA9))
            emojis?.add(Utils.getString(0xAE))
            emojis?.add(Utils.getString(0x2122))
            emojis?.add(Utils.getString(0x23, 0x20E3))
            emojis?.add(Utils.getString(0x2A, 0x20E3))
            emojis?.add(Utils.getString(0x30, 0x20E3))
            emojis?.add(Utils.getString(0x31, 0x20E3))
            emojis?.add(Utils.getString(0x32, 0x20E3))
            emojis?.add(Utils.getString(0x33, 0x20E3))
            emojis?.add(Utils.getString(0x34, 0x20E3))
            emojis?.add(Utils.getString(0x35, 0x20E3))
            emojis?.add(Utils.getString(0x36, 0x20E3))
            emojis?.add(Utils.getString(0x37, 0x20E3))
            emojis?.add(Utils.getString(0x38, 0x20E3))
            emojis?.add(Utils.getString(0x39, 0x20E3))
            emojis?.add(Utils.getString(0x1F51F))
            emojis?.add(Utils.getString(0x1F4AF))
            emojis?.add(Utils.getString(0x1F520))
            emojis?.add(Utils.getString(0x1F521))
            emojis?.add(Utils.getString(0x1F522))
            emojis?.add(Utils.getString(0x1F523))
            emojis?.add(Utils.getString(0x1F524))
            emojis?.add(Utils.getString(0x1F170))
            emojis?.add(Utils.getString(0x1F18E))
            emojis?.add(Utils.getString(0x1F171))
            emojis?.add(Utils.getString(0x1F191))
            emojis?.add(Utils.getString(0x1F192))
            emojis?.add(Utils.getString(0x1F193))
            emojis?.add(Utils.getString(0x2139))
            emojis?.add(Utils.getString(0x1F194))
            emojis?.add(Utils.getString(0x24C2))
            emojis?.add(Utils.getString(0x1F195))
            emojis?.add(Utils.getString(0x1F196))
            emojis?.add(Utils.getString(0x1F17E))
            emojis?.add(Utils.getString(0x1F197))
            emojis?.add(Utils.getString(0x1F17F))
            emojis?.add(Utils.getString(0x1F198))
            emojis?.add(Utils.getString(0x1F199))
            emojis?.add(Utils.getString(0x1F19A))
            emojis?.add(Utils.getString(0x1F201))
            emojis?.add(Utils.getString(0x1F202))
            emojis?.add(Utils.getString(0x1F237))
            emojis?.add(Utils.getString(0x1F236))
            emojis?.add(Utils.getString(0x1F22F))
            emojis?.add(Utils.getString(0x1F250))
            emojis?.add(Utils.getString(0x1F239))
            emojis?.add(Utils.getString(0x1F21A))
            emojis?.add(Utils.getString(0x1F232))
            emojis?.add(Utils.getString(0x1F251))
            emojis?.add(Utils.getString(0x1F238))
            emojis?.add(Utils.getString(0x1F234))
            emojis?.add(Utils.getString(0x1F233))
            emojis?.add(Utils.getString(0x3297))
            emojis?.add(Utils.getString(0x3299))
            emojis?.add(Utils.getString(0x1F23A))
            emojis?.add(Utils.getString(0x1F235))
            emojis?.add(Utils.getString(0x25AA))
            emojis?.add(Utils.getString(0x25AB))
            emojis?.add(Utils.getString(0x25FB))
            emojis?.add(Utils.getString(0x25FC))
            emojis?.add(Utils.getString(0x25FD))
            emojis?.add(Utils.getString(0x25FE))
            emojis?.add(Utils.getString(0x2B1B))
            emojis?.add(Utils.getString(0x2B1C))
            emojis?.add(Utils.getString(0x1F536))
            emojis?.add(Utils.getString(0x1F537))
            emojis?.add(Utils.getString(0x1F538))
            emojis?.add(Utils.getString(0x1F539))
            emojis?.add(Utils.getString(0x1F53A))
            emojis?.add(Utils.getString(0x1F53B))
            emojis?.add(Utils.getString(0x1F4A0))
            emojis?.add(Utils.getString(0x1F518))
            emojis?.add(Utils.getString(0x1F532))
            emojis?.add(Utils.getString(0x1F533))
            emojis?.add(Utils.getString(0x26AA))
            emojis?.add(Utils.getString(0x26AB))
            emojis?.add(Utils.getString(0x1F534))
            emojis?.add(Utils.getString(0x1F535))

            return emojis

        }

    }

}